### ISSUE TITLE
Display name item without fold level

### ISSUE THREAD

**Issue by morganfuchs** [medisapp/medisapp.github.io#10]
Hello, I just discovered your tool which I find very well done. However, would it be possible to display the name of the entries in the parent hierarchy? 

<img width="399" alt="image" src="https://user-images.githubusercontent.com/5873439/158443540-31c299e3-d270-49d4-8ee3-a92cf1af59df.png">

This will make the listing more enjoyable! Thanks

**Comment by luin** [comment]
Hi @morganfuchs 👋 

Thanks for using Medis! We are going to add an option to only show the last part of key names as shown in the following screenshot. Is this what you asked?

<img width="573" alt="CleanShot 2022-04-21 at 19 12 40@2x" src="https://user-images.githubusercontent.com/635902/164446375-f781ba1f-81e7-4254-b699-b72101369790.png">

**Comment by morganfuchs** [comment]
Yes perfect ! With this option, I will use your tool all time :-)

**Comment by luin** [comment]
Released with v2.8.2. In this version, we also provide an option for key type style customization which should be useful for long key names.

Feel free to lmk if there is anything else that can be improved 😄
