### ISSUE TITLE
PHP serialized data support

### ISSUE THREAD

**Issue by luin** [medisapp/medisapp.github.io#13]
https://www.php.net/manual/en/function.serialize.php

**Comment by jjjrmy** [comment]
+1 on this, Laravel saves serialized data - so it's a bit painful to view

**Comment by luin** [comment]
A general idea is the parse serialized data to JSON and display it in the JSON viewer. However, it seems tricky when it comes to PHP object. Ex `O:8:"stdClass":2:{s:4:"John";d:3.14;s:4:"Jane";d:2.718;}`, if we display as:

```json
{
  "John": 3.124,
  "Jane": 2.718
}
```

We lost the stdClass part, which, if users make changes and save it back, it's very likely not what they expected.

**Comment by luin** [comment]
Added in 2.8.8. Closing
