### ISSUE TITLE
[Feature Request] 在菜单栏切换窗口上显示配置“名称”

### ISSUE THREAD

**Issue by blackhuman** [medisapp/medisapp.github.io#14]
现在在菜单栏的切换窗口上显示的名字为host:port，而不是配置用的name，希望如窗口右侧一样显示name。如果是因为统计过需求并特意设计成这种显示方式的，请忽略这个请求。

![image](https://user-images.githubusercontent.com/2269615/165913801-2d2a5479-a663-49d8-b486-d1d7a0aecb0d.png)

**Comment by luin** [comment]
感谢建议，已经加入到排期中。

**Comment by luin** [comment]
2.8.5 中已经支持。
