### ISSUE TITLE
Increased selection on `Max fold level` setting

### ISSUE THREAD

**Issue by pqt** [medisapp/medisapp.github.io#20]
Hi! So far loving the trial of the app. Looking to bring it into use for myself (and perhaps more broadly to an organization once I have time to build it into my workflow).

Excellent job on it.

One thing that I am already struggling with is in `Settings > Key Browser > Max fold level` and it's maximum size of 4.

I would love this to be opened up (either to have many more options up to and included ~20) or to accept any number value so that it could be manually set.

If there is some sort of technical limitation to this, I completely understand but wanted to request this here for consideration.

Cheers!

**Comment by luin** [comment]
Hey @pqt 👋 ,

Thanks for using Medis. I think it's reasonable to make it an input to accept any value. Going to add this in the next version (should be released within two weeks).

**Comment by luin** [comment]
Added in v2.8.7. It keeps using a selector for simplicity but increases the limit to 20. Let me know if there is anything further I can help with.
