### ISSUE TITLE
Option to default Viewer and Formatter

### ISSUE THREAD

**Issue by joshcalloway** [medisapp/medisapp.github.io#24]
It would be nice to be able to set the default viewer and formatter on the editor pane

**Comment by luin** [comment]
Hey @joshcalloway 👋 ,

Thanks for the feedback! Can you elaborate a little bit more on the use case? Medis detects the content format and pick the default viewer and formatted automatically. Doesn't it work for you? Do you want to make the option global-level or connection-level?

**Comment by joshcalloway** [comment]
For some reason my viewer defaults to plain no matter the content.  Presently I am looking a several json items and the viewer changes to plain every time I click anything even if I manually set it to json.   I would think a global level would work best but either would solve my issue.

**Comment by luin** [comment]
That makes sense. I've added the setting to the roadmap. In the meantime, I'd like to understand if there are anything we need to do in order to fix the viewer issue. Is your data a valid JSON? Can you try to paste them in https://jsonlint.com/ to validate? If they are, Medis should be able to pick the JSON viewer automatically.

**Comment by joshcalloway** [comment]
You're correct in that the source is not valid JSON.  Thanks for the follow up and it would still be nice to force it into the JSON viewer but I see why it isn't automatically doing it.

**Comment by luin** [comment]
Hey @joshcalloway, in 2.8.17, you can set up a content rule in order to make JSON the default viewer. Feel free to let me know if there are any issues!

https://docs.getmedis.com/content-rules
