### ISSUE TITLE
Json view improve

### ISSUE THREAD

**Issue by Milesians** [medisapp/medisapp.github.io#3]
Can medis provide the beauty function of json?

**Comment by luin** [comment]
It's already supported in the latest version. It's not enabled by default but you can find the setting on the Editor panel:

<img width="572" alt="CleanShot 2021-12-08 at 10 00 50@2x" src="https://user-images.githubusercontent.com/635902/145135155-86e9bbd4-f023-437b-b034-cd641e1b943d.png">

**Comment by Milesians** [comment]
> 

Thank you , I got it.

**Comment by Milesians** [comment]
> It's already supported in the latest version. It's not enabled by default but you can find the setting on the Editor panel:
> 
> <img alt="CleanShot 2021-12-08 at 10 00 50@2x" width="572" src="https://user-images.githubusercontent.com/635902/145135155-86e9bbd4-f023-437b-b034-cd641e1b943d.png">

Thank you , I got it.
