### ISSUE TITLE
Cluster support

### ISSUE THREAD

**Issue by L-fushen** [medisapp/medisapp.github.io#4]

**Comment by luin** [comment]
感谢反馈！目前还在计划中。

Thanks for the feedback, it's on the roadmap. As a workaround, you can connect to the node directly.

**Comment by gregorg** [comment]
any updates ?

**Comment by luin** [comment]
Hi @gregorg 👋,

It has been in the top three of our roadmap, though it was delayed for a long time because of the difficulty. I expect to have this feature live in October.

**Comment by luin** [comment]
It was already delivered in the version released in October so closing it. Feel free to reopen when there are issues.
