### ISSUE TITLE
Allow line breaks in Command Query when using EVAL

### ISSUE THREAD

**Issue by careerlister** [medisapp/medisapp.github.io#5]
It would be nice to have line breaks when typing in an EVAL string so that it is developer friendly.  A single line with a longer script makes difficult to develop on MEDIS.

Example: 
EVAL "
local abc = 123
local def = abc * 987
return def
"

vs 

EVAL "local abc = 123 local def = abc * 987 return def".  <= difficult to see where one line would end and the next begins and this is a small script of 3 lines normally.

**Comment by luin** [comment]
Nice suggestion. Added to the roadmap.

There are also two related improvements on the roadmap:
1. Syntax highlighting for the command query view.
2. A dedicated view to run Lua scripts.

**Comment by luin** [comment]
<img width="955" alt="CleanShot 2022-04-09 at 17 48 19@2x" src="https://user-images.githubusercontent.com/635902/162566868-bfe0f84f-4c85-44dd-9e15-9e2b5958af8d.png">

In the upcoming release, we will be adding several features to the command query view:

1. Multiline argument support.
2. Improved syntax highlighting.
3. Command auto complete.

Please refer to the screenshots and feel free to contact if there are other related requirements not included.

**Comment by luin** [comment]
Added in 2.8.1.

**Comment by careerlister** [comment]
Congrats!   Thank you for this!
