### ISSUE TITLE
Format JSON

### ISSUE THREAD

**Issue by ErwinSteffens** [medisapp/medisapp.github.io#6]
Just a small request:

It would be nice if you could add formatting for JSON content in Medis.

**Comment by luin** [comment]
Hi @ErwinSteffens ,

It's already supported behind a setting. You can find it on the preference window (Editor panel). Let me know if that solves your issue.

**Comment by ErwinSteffens** [comment]
Ah, awesome!

I did not see it in this list, so I figured it was not supported:

![image](https://user-images.githubusercontent.com/6931114/147733820-95bfbcda-0ba5-4b65-bb06-0824a808965e.png)

Thank you!
