### ISSUE TITLE
是否在Command Query中添加命令提示？

### ISSUE THREAD

**Issue by simonyang81** [medisapp/medisapp.github.io#9]
例如redis-cli中可以按tab自动补全命令

**Comment by luin** [comment]
Hi @simonyang81 👋 ,

现在已经在右侧支持同步显示命令文档了，所以自动补全功能的优先级会比较低。

**Comment by luin** [comment]
<img width="955" alt="CleanShot 2022-04-09 at 17 48 19@2x" src="https://user-images.githubusercontent.com/635902/162566868-bfe0f84f-4c85-44dd-9e15-9e2b5958af8d.png">

在即将发布的下个版本中会加入自动补全功能。如果有其他建议欢迎随时联系。

**Comment by luin** [comment]
已在 2.8.1 中支持。
